services:
  ollama-custom:
    build: .
    container_name: ollama-custom
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_ORIGINS=*
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  ollama-data:
    driver: local